---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 3000, host: 3000, auto_correct: true}]  # uchiwa
  - ["forwarded_port", {guest: 15672,   host: 15672, auto_correct: true}]  # Rabbitmq manage
  # - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}] # ssl

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[rnbsensu::default]
    attributes:
